
# ResNet18 protocol 1
FATHER_DIR=output/bc/ResNet18_Adam/HiFi+CelebA+SIW/; CUDA_VISIBLE_DEVICES=0 python train.py --trainer bc_ewc TRAIN.PROTOCOL 1 OUTPUT_DIR output/bc_ewc/ResNet18_Adam/protocol1/ TRAIN.INIT ${FATHER_DIR}/ckpt/best.ckpt TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 200 MODEL.ARCH resnet18 DATA.NUM_WORKERS 3 DATA.BATCH_SIZE 20 TRAIN.OPTIM.TYPE Adam DATA.IN_SIZE 224 TRAIN.INIT_LR 1e-4 TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 500 MODEL.FIX_BACKBONE True TEST.BATCH_SIZE 128



# ResNet18 protocol 2
FATHER_DIR=output/bc/ResNet18_Adam/HiFi+CelebA+SIW/; CUDA_VISIBLE_DEVICES=3 python train.py --trainer bc_ewc TRAIN.PROTOCOL 2 OUTPUT_DIR output/bc_ewc/ResNet18_Adam/protocol2/ TRAIN.INIT ${FATHER_DIR}/ckpt/best.ckpt TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 200 MODEL.ARCH resnet18 DATA.NUM_WORKERS 3 DATA.BATCH_SIZE 20 TRAIN.OPTIM.TYPE Adam DATA.IN_SIZE 224 TRAIN.INIT_LR 1e-4 TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 500 MODEL.FIX_BACKBONE True TEST.BATCH_SIZE 128

