
# ResNet18 protocol 1
FATHER_DIR=output/bc/ResNet18_Adam/HiFi+CelebA+SIW/; CUDA_VISIBLE_DEVICES=1 python train.py --trainer bc_ewc MODEL.ARCH resnet18 TRAIN.PROTOCOL 1 OUTPUT_DIR output/bc_ewc/ResNet18_Adam/protocol1/ TRAIN.INIT ${FATHER_DIR}/ckpt/best.ckpt TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 200 MODEL.ARCH resnet18 DATA.NUM_WORKERS 3 DATA.BATCH_SIZE 20 TRAIN.OPTIM.TYPE Adam DATA.IN_SIZE 224 TRAIN.INIT_LR 1e-4 TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 500 MODEL.FIX_BACKBONE True TEST.BATCH_SIZE 128 TRAIN.EWC_ONLINE False
FATHER_DIR=output/bc/ResNet18_Adam/HiFi+CelebA+SIW/; CUDA_VISIBLE_DEVICES=0 python train.py --trainer bc_ewc MODEL.ARCH resnet18 TRAIN.PROTOCOL 1 OUTPUT_DIR output/bc_ewc/ResNet18_Adam/protocol1_online/ TRAIN.INIT ${FATHER_DIR}/ckpt/best.ckpt TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 200 MODEL.ARCH resnet18 DATA.NUM_WORKERS 3 DATA.BATCH_SIZE 20 TRAIN.OPTIM.TYPE Adam DATA.IN_SIZE 224 TRAIN.INIT_LR 1e-4 TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 500 MODEL.FIX_BACKBONE True TEST.BATCH_SIZE 128 TRAIN.EWC_ONLINE True

# protocol 1 offline
FATHER_DIR=output/bc/ResNet18_Adam/HiFi+CelebA+SIW/; CUDA_VISIBLE_DEVICES=0 python train.py --trainer bc_ewc MODEL.ARCH resnet18 TRAIN.PROTOCOL 1 OUTPUT_DIR output/bc_ewc/ResNet18_Adam/protocol1/ TRAIN.INIT ${FATHER_DIR}/ckpt/best.ckpt TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 200 MODEL.ARCH resnet18 DATA.NUM_WORKERS 3 DATA.BATCH_SIZE 20 TRAIN.OPTIM.TYPE Adam DATA.IN_SIZE 224 TRAIN.INIT_LR 1e-4 TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 500 MODEL.FIX_BACKBONE True TEST.BATCH_SIZE 128 TRAIN.EWC_ONLINE True



# ResNet18 protocol 2
FATHER_DIR=output/bc/ResNet18_Adam/HiFi+CelebA+SIW/; CUDA_VISIBLE_DEVICES=3 python train.py --trainer bc_ewc MODEL.ARCH resnet18 TRAIN.PROTOCOL 2 OUTPUT_DIR output/bc_ewc/ResNet18_Adam/protocol2/ TRAIN.INIT ${FATHER_DIR}/ckpt/best.ckpt TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 200 MODEL.ARCH resnet18 DATA.NUM_WORKERS 3 DATA.BATCH_SIZE 20 TRAIN.OPTIM.TYPE Adam DATA.IN_SIZE 224 TRAIN.INIT_LR 1e-4 TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 500 MODEL.FIX_BACKBONE True TEST.BATCH_SIZE 128


# Adapter protocol 1
FATHER_DIR=output/vit_adapter/vit_base_patch16_224_Adam_pretrain_update_adapter/HiFi+CelebA+SIW; CUDA_VISIBLE_DEVICES=0 python train.py --trainer bc_ewc MODEL.ARCH adapter-vit_base_patch16_224 TRAIN.PROTOCOL 1 OUTPUT_DIR output/bc_ewc/vit_adapter/protocol1/ TRAIN.INIT ${FATHER_DIR}/ckpt/best.ckpt TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 500 DATA.NUM_WORKERS 3 DATA.BATCH_SIZE 20 TRAIN.OPTIM.TYPE Adam DATA.IN_SIZE 224 TRAIN.INIT_LR 1e-4 TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 500 MODEL.FIX_BACKBONE True TEST.BATCH_SIZE 128 TRAIN.EWC_ONLINE False

# Adapter protocol 2
FATHER_DIR=output/vit_adapter/vit_base_patch16_224_Adam_pretrain_update_adapter/HiFi+CelebA+SIW; CUDA_VISIBLE_DEVICES=3 python train.py --trainer bc_ewc MODEL.ARCH adapter-vit_base_patch16_224 TRAIN.PROTOCOL 1 OUTPUT_DIR output/bc_ewc/vit_adapter/protocol1_online/ TRAIN.INIT ${FATHER_DIR}/ckpt/best.ckpt TRAIN.VAL_FREQ 10 TRAIN.EPOCHS 500 DATA.NUM_WORKERS 3 DATA.BATCH_SIZE 20 TRAIN.OPTIM.TYPE Adam DATA.IN_SIZE 224 TRAIN.INIT_LR 1e-4 TRAIN.VAL_FREQ 1 TRAIN.EPOCHS 2 MODEL.FIX_BACKBONE True TEST.BATCH_SIZE 128 TRAIN.EWC_ONLINE True

